# Generated by Django 4.2.7 on 2023-11-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_tag_scopes_article_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletag',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
