# Generated by Django 4.2.7 on 2023-11-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0008_remove_article_scopes"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="scopes",
            field=models.ManyToManyField(related_name="scopes", to="articles.tag"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="subject",
            field=models.CharField(max_length=200),
        ),
    ]
