# Generated by Django 4.2.7 on 2023-11-13 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0012_alter_tag_options_tag_article_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articletag",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="articletag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scopes",
                to="articles.tag",
            ),
        ),
    ]
